# Aliases

alias ag="sudo apt-get"
alias ac="sudo apt-cache"
alias aar="sudo apt-add-repository -y"

# apt-get [update|upgrade|dist-upgrade|install|remove|purge|source|build-dep|check|download|clean|autoclean|autoremove|changelog]
alias agu="ag update"
alias agup="ag upgrade"
alias agdu="ag dist-upgrade"
alias agi="ag install"
alias agsup="agi --only-upgrade"
alias agr="ag remove"
alias agp="ag purge"
alias ags="ag source"
alias agbd="ag build-dep"
alias agc="ag check"
alias agd="ag download"
alias agcl="ag clean"
alias agac="ag autoclean"
alias agar="ag autoremove"
alias agch="ag changelog"

# apt-cache [show-pkg|stats|showsrc|dump|dumpavail|unmet|show|search|depends|rdepends|pkgnames|dotty|xvcg|policy|madison]
alias acsp="ac showpkg"
alias acst="ac stats"
alias acss="ac showsrc"
alias acd="ac dump"
alias acda="ac dumpavail"
alias acu="ac unmet"
alias acsh="ac show"
alias acs="ac search"
alias acd="ac depends"
alias acrd="ac rdepends"
alias acpk="ac pkgnames"
alias acd="ac dotty"
alias acx="ac xvcg"
alias acp="ac policy"
alias acm="ac madison"
